import os
from datetime import datetime

DATA_DIR_PATH = "./data"
RAW_DATA_DIR_PATH = os.path.join(DATA_DIR_PATH, "raw")
PROC_DATA_DIR_PATH = os.path.join(DATA_DIR_PATH, "processed")

RESULTS_SWAT_TRAIN_PATH = os.path.join(DATA_DIR_PATH, "swat_results_train.parquet")
RESULTS_SWAT_TEST_PATH = os.path.join(DATA_DIR_PATH, "swat_results_test.parquet")


# SWaT
SWAT_RAW_FOLDER_PATH = os.path.join(RAW_DATA_DIR_PATH, "SWaT.A1 _ A2_Dec 2015")
SWAT_RAW_LABEL_PATH = os.path.join(SWAT_RAW_FOLDER_PATH, "List_of_attacks_Final.xlsx")
SWAT_RAW_NORMAL_V0_PATH = os.path.join(
    SWAT_RAW_FOLDER_PATH, "Physical", "SWaT_Dataset_Normal_v0.xlsx"
)
SWAT_RAW_NORMAL_V1_PATH = os.path.join(
    SWAT_RAW_FOLDER_PATH, "Physical", "SWaT_Dataset_Normal_v1.xlsx"
)
SWAT_RAW_ATTACK_V0_PATH = os.path.join(
    SWAT_RAW_FOLDER_PATH, "Physical", "SWaT_Dataset_Attack_v0.xlsx"
)

SWAT_PARQUET_NORMAL_V0_PATH = os.path.join(
    PROC_DATA_DIR_PATH, "swat_dataset_normal_v0.parquet"
)
SWAT_PARQUET_NORMAL_V1_PATH = os.path.join(
    PROC_DATA_DIR_PATH, "swat_dataset_normal_v1.parquet"
)
SWAT_PARQUET_ATTACK_V0_PATH = os.path.join(
    PROC_DATA_DIR_PATH, "swat_dataset_attack_v0.parquet"
)

SWAT_TRAIN_PATH = os.path.join(PROC_DATA_DIR_PATH, "swat_train.parquet")
SWAT_VAL_PATH = os.path.join(PROC_DATA_DIR_PATH, "swat_val.parquet")
SWAT_LABEL_PATH = os.path.join(PROC_DATA_DIR_PATH, "labels.csv")
SWAT_MIN_DATE = datetime(2015, 12, 22)
SWAT_MAX_DATE = datetime(2016, 1, 2)


SWAT_SENSOR_COLS = [
    "FIT101",
    "LIT101",
    "MV101",
    "P101",
    "P102",
    "AIT201",
    "AIT202",
    "AIT203",
    "FIT201",
    "MV201",
    "P201",
    "P202",
    "P203",
    "P204",
    "P205",
    "P206",
    "DPIT301",
    "FIT301",
    "LIT301",
    "MV301",
    "MV302",
    "MV303",
    "MV304",
    "P301",
    "P302",
    "AIT401",
    "AIT402",
    "FIT401",
    "LIT401",
    "P401",
    "P402",
    "P403",
    "P404",
    "UV401",
    "AIT501",
    "AIT502",
    "AIT503",
    "AIT504",
    "FIT501",
    "FIT502",
    "FIT503",
    "FIT504",
    "P501",
    "P502",
    "PIT501",
    "PIT502",
    "PIT503",
    "FIT601",
    "P601",
    "P602",
    "P603",
]

SWAT_SYMBOLS_MAP = {
    "Comp_1": ["FIT101", "LIT101", "MV101", "P101", "P102"],
    "Comp_2": [
        "AIT201",
        "AIT202",
        "AIT203",
        "FIT201",
        "MV201",
        "P201",
        "P202",
        "P203",
        "P204",
        "P205",
        "P206",
    ],
    "Comp_3": [
        "DPIT301",
        "FIT301",
        "LIT301",
        "MV301",
        "MV302",
        "MV303",
        "MV304",
        "P301",
        "P302",
    ],
    "Comp_4": [
        "AIT401",
        "AIT402",
        "FIT401",
        "LIT401",
        "P401",
        "P402",
        "P403",
        "P404",
        "UV401",
    ],
    "Comp_5": [
        "AIT501",
        "AIT502",
        "AIT503",
        "AIT504",
        "FIT501",
        "FIT502",
        "FIT503",
        "FIT504",
        "P501",
        "P502",
        "PIT501",
        "PIT502",
        "PIT503",
    ],
    "Comp_6": ["FIT601", "P601", "P602", "P603"],
}


BERFIPL_SIGNALS_MAP = {
    "mixer_partial0.valve_V204": [
        "mixer_partial0.valve_V204.m_flow",
        "mixer_partial0.valve_V204.port_a.m_flow",
        "mixer_partial0.valve_V204.port_a.p",
        "mixer_partial0.valve_V204.port_b.m_flow",
        "mixer_partial0.valve_V204.port_b.p",
    ],
    "mixer_partial0.pipe3": [
        "mixer_partial0.pipe3.flowModel.m_flows[1]",
        "mixer_partial0.pipe3.port_a.m_flow",
        "mixer_partial0.pipe3.port_a.p",
        "mixer_partial0.pipe3.port_b.m_flow",
        "mixer_partial0.pipe3.port_b.p",
    ],
    "mixer_partial0.pipe_out": [
        "mixer_partial0.pipe_out.flowModel.m_flows[1]",
        "mixer_partial0.pipe_out.port_a.m_flow",
        "mixer_partial0.pipe_out.port_a.p",
        "mixer_partial0.pipe_out.port_b.m_flow",
        "mixer_partial0.pipe_out.port_b.p",
    ],
    "mixer_partial0.pipe5": [
        "mixer_partial0.pipe5.flowModel.m_flows[1]",
        "mixer_partial0.pipe5.port_a.m_flow",
        "mixer_partial0.pipe5.port_a.p",
        "mixer_partial0.pipe5.port_b.m_flow",
    ],
    "mixer_partial0.pipe": [
        "mixer_partial0.pipe.flowModel.m_flows[1]",
        "mixer_partial0.pipe.port_a.m_flow",
        "mixer_partial0.pipe.port_a.p",
        "mixer_partial0.pipe.port_b.m_flow",
        "mixer_partial0.pipe.port_b.p",
    ],
    "mixer_partial0.tank_B203": [
        "mixer_partial0.tank_B203.level",
        "mixer_partial0.tank_B203.fluidVolume",
        "mixer_partial0.tank_B203.ports[1].m_flow",
        "mixer_partial0.tank_B203.ports[2].m_flow",
    ],
    "mixer_partial0.pump_P201": [
        "mixer_partial0.pump_P201.N_in",
        "mixer_partial0.pump_P201.fluidVolume",
        "mixer_partial0.pump_P201.m_flow",
        "mixer_partial0.pump_P201.m_flow_single",
        "mixer_partial0.pump_P201.N_in_internal",
        "mixer_partial0.pump_P201.port_a.m_flow",
        "mixer_partial0.pump_P201.port_a.p",
        "mixer_partial0.pump_P201.port_b.m_flow",
        "mixer_partial0.pump_P201.port_b.p",
    ],
    "mixer_partial0.pipe2": [
        "mixer_partial0.pipe2.flowModel.m_flows[1]",
        "mixer_partial0.pipe2.port_a.m_flow",
        "mixer_partial0.pipe2.port_a.p",
        "mixer_partial0.pipe2.port_b.m_flow",
        "mixer_partial0.pipe2.port_b.p",
    ],
    "mixer_partial0.valve_V203": [
        "mixer_partial0.valve_V203.m_flow",
        "mixer_partial0.valve_V203.port_a.m_flow",
        "mixer_partial0.valve_V203.port_a.p",
        "mixer_partial0.valve_V203.port_b.m_flow",
        "mixer_partial0.valve_V203.port_b.p",
    ],
    "mixer_partial0.valve_in1": [
        "mixer_partial0.valve_in1.m_flow",
        "mixer_partial0.valve_in1.port_a.m_flow",
        "mixer_partial0.valve_in1.port_a.p",
        "mixer_partial0.valve_in1.port_b.m_flow",
        "mixer_partial0.valve_in1.port_b.p",
    ],
    "mixer_partial0.valveDiscrete": [
        "mixer_partial0.valveDiscrete.m_flow",
        "mixer_partial0.valveDiscrete.port_a.m_flow",
        "mixer_partial0.valveDiscrete.port_a.p",
        "mixer_partial0.valveDiscrete.port_b.m_flow",
        "mixer_partial0.valveDiscrete.port_b.p",
    ],
    "mixer_partial0.valve_leaking": [
        "mixer_partial0.valve_leaking.m_flow",
        "mixer_partial0.valve_leaking.opening",
        "mixer_partial0.valve_leaking.port_a.m_flow",
        "mixer_partial0.valve_leaking.port_a.p",
        "mixer_partial0.valve_leaking.port_b.m_flow",
        "mixer_partial0.valve_leaking.port_b.p",
    ],
    "mixer_partial0.port_out": ["mixer_partial0.port_out.m_flow"],
    "mixer_partial0.tank_B202": [
        "mixer_partial0.tank_B202.level",
        "mixer_partial0.tank_B202.fluidVolume",
        "mixer_partial0.tank_B202.ports[1].m_flow",
        "mixer_partial0.tank_B202.ports[2].m_flow",
    ],
    "mixer_partial0.pipe1": [
        "mixer_partial0.pipe1.flowModel.m_flows[1]",
        "mixer_partial0.pipe1.port_a.m_flow",
        "mixer_partial0.pipe1.port_a.p",
        "mixer_partial0.pipe1.port_b.m_flow",
        "mixer_partial0.pipe1.port_b.p",
    ],
    "mixer_partial0.tank_B201": [
        "mixer_partial0.tank_B201.level",
        "mixer_partial0.tank_B201.fluidVolume",
        "mixer_partial0.tank_B201.ports[1].m_flow",
        "mixer_partial0.tank_B201.ports[2].m_flow",
    ],
    "mixer_partial0.port_in2": ["mixer_partial0.port_in2.m_flow"],
    "source1": [
        "source1.pipe_out.flowModel.m_flows[1]",
        "source1.pipe_out.port_a.m_flow",
        "source1.pipe_out.port_b.m_flow",
        "source1.pipe_out.port_b.p",
        "source1.port_out.m_flow",
        "source1.source.ports[1].m_flow",
        "source1.volumeFlowRate.port_a.m_flow",
        "source1.volumeFlowRate.port_b.m_flow",
    ],
    "mixer_partial0.pipe4": [
        "mixer_partial0.pipe4.flowModel.m_flows[1]",
        "mixer_partial0.pipe4.port_a.m_flow",
        "mixer_partial0.pipe4.port_a.p",
        "mixer_partial0.pipe4.port_b.m_flow",
        "mixer_partial0.pipe4.port_b.p",
    ],
    "mixer_partial0.valve_clogging": [
        "mixer_partial0.valve_clogging.port_b.p",
        "mixer_partial0.valve_clogging.m_flow",
        "mixer_partial0.valve_clogging.opening",
        "mixer_partial0.valve_clogging.port_a.m_flow",
        "mixer_partial0.valve_clogging.port_a.p",
        "mixer_partial0.valve_clogging.port_b.m_flow",
    ],
    "source0": [
        "source0.pipe_out.flowModel.m_flows[1]",
        "source0.pipe_out.port_a.m_flow",
        "source0.pipe_out.port_b.m_flow",
        "source0.pipe_out.port_b.p",
        "source0.port_out.m_flow",
        "source0.source.ports[1].m_flow",
        "source0.volumeFlowRate.port_a.m_flow",
        "source0.volumeFlowRate.port_b.m_flow",
    ],
    "mixer_partial0.valve_V201": [
        "mixer_partial0.valve_V201.m_flow",
        "mixer_partial0.valve_V201.port_a.m_flow",
        "mixer_partial0.valve_V201.port_a.p",
        "mixer_partial0.valve_V201.port_b.m_flow",
        "mixer_partial0.valve_V201.port_b.p",
    ],
    "mixer_partial0.tank_reservoir": [
        "mixer_partial0.tank_reservoir.level",
        "mixer_partial0.tank_reservoir.fluidVolume",
        "mixer_partial0.tank_reservoir.ports[1].m_flow",
        "mixer_partial0.tank_reservoir.ports[2].m_flow",
        "mixer_partial0.tank_reservoir.ports[3].m_flow",
        "mixer_partial0.tank_reservoir.ports[4].m_flow",
    ],
    "mixer_partial0.port_in1": ["mixer_partial0.port_in1.m_flow"],
    "source2": [
        "source2.pipe_out.flowModel.m_flows[1]",
        "source2.pipe_out.port_a.m_flow",
        "source2.pipe_out.port_b.m_flow",
        "source2.pipe_out.port_b.p",
        "source2.port_out.m_flow",
        "source2.source.ports[1].m_flow",
        "source2.volumeFlowRate.port_a.m_flow",
        "source2.volumeFlowRate.port_b.m_flow",
    ],
    "mixer_partial0.valve_in2": [
        "mixer_partial0.valve_in2.m_flow",
        "mixer_partial0.valve_in2.port_a.m_flow",
        "mixer_partial0.valve_in2.port_a.p",
        "mixer_partial0.valve_in2.port_b.m_flow",
        "mixer_partial0.valve_in2.port_b.p",
    ],
    "mixer_partial0.valve_V202": [
        "mixer_partial0.valve_V202.m_flow",
        "mixer_partial0.valve_V202.port_a.m_flow",
        "mixer_partial0.valve_V202.port_a.p",
        "mixer_partial0.valve_V202.port_b.m_flow",
        "mixer_partial0.valve_V202.port_b.p",
    ],
    "mixer_partial0.sink": ["mixer_partial0.sink.ports[1].m_flow"],
    "mixer_partial0.port_in3": ["mixer_partial0.port_in3.m_flow"],
    "mixer_partial0.tank_B204": [
        "mixer_partial0.tank_B204.level",
        "mixer_partial0.tank_B204.fluidVolume",
        "mixer_partial0.tank_B204.ports[1].m_flow",
        "mixer_partial0.tank_B204.ports[2].m_flow",
    ],
    "sink0": [
        "sink0.pipe.flowModel.m_flows[1]",
        "sink0.pipe.port_a.m_flow",
        "sink0.pipe.port_a.p",
        "sink0.pipe.port_b.m_flow",
        "sink0.port_in.m_flow",
        "sink0.sink.ports[1].m_flow",
        "sink0.volumeFlowRate.port_a.m_flow",
        "sink0.volumeFlowRate.port_b.m_flow",
    ],
    "mixer_partial0.valve_in3": [
        "mixer_partial0.valve_in3.m_flow",
        "mixer_partial0.valve_in3.port_a.m_flow",
        "mixer_partial0.valve_in3.port_a.p",
        "mixer_partial0.valve_in3.port_b.m_flow",
        "mixer_partial0.valve_in3.port_b.p",
    ],
}

BERFIPL_COLS = [
    "mixer_partial0.tank_B201.level",
    "mixer_partial0.tank_B202.level",
    "mixer_partial0.tank_B203.level",
    "mixer_partial0.tank_B204.level",
    "mixer_partial0.tank_reservoir.level",
    "mixer_partial0.pipe4.flowModel.m_flows[1]",
    "mixer_partial0.pump_P201.N_in",
    "mixer_partial0.pump_P201.fluidVolume",
    "mixer_partial0.pump_P201.m_flow",
    "mixer_partial0.pump_P201.m_flow_single",
    "mixer_partial0.valve_V201.m_flow",
    "mixer_partial0.valve_V202.m_flow",
    "mixer_partial0.valve_V203.m_flow",
    "mixer_partial0.valve_V204.m_flow",
    "mixer_partial0.valve_clogging.port_b.p",
    "mixer_partial0.valve_leaking.m_flow",
    "sink0.pipe.flowModel.m_flows[1]",
    "source0.pipe_out.flowModel.m_flows[1]",
    "source1.pipe_out.flowModel.m_flows[1]",
    "source2.pipe_out.flowModel.m_flows[1]",
    "mixer_partial0.pipe.flowModel.m_flows[1]",
    "mixer_partial0.pipe.port_a.m_flow",
    "mixer_partial0.pipe.port_a.p",
    "mixer_partial0.pipe.port_b.m_flow",
    "mixer_partial0.pipe.port_b.p",
    "mixer_partial0.pipe1.flowModel.m_flows[1]",
    "mixer_partial0.pipe1.port_a.m_flow",
    "mixer_partial0.pipe1.port_a.p",
    "mixer_partial0.pipe1.port_b.m_flow",
    "mixer_partial0.pipe1.port_b.p",
    "mixer_partial0.pipe2.flowModel.m_flows[1]",
    "mixer_partial0.pipe2.port_a.m_flow",
    "mixer_partial0.pipe2.port_a.p",
    "mixer_partial0.pipe2.port_b.m_flow",
    "mixer_partial0.pipe2.port_b.p",
    "mixer_partial0.pipe3.flowModel.m_flows[1]",
    "mixer_partial0.pipe3.port_a.m_flow",
    "mixer_partial0.pipe3.port_a.p",
    "mixer_partial0.pipe3.port_b.m_flow",
    "mixer_partial0.pipe3.port_b.p",
    "mixer_partial0.pipe4.port_a.m_flow",
    "mixer_partial0.pipe4.port_a.p",
    "mixer_partial0.pipe4.port_b.m_flow",
    "mixer_partial0.pipe4.port_b.p",
    "mixer_partial0.pipe5.flowModel.m_flows[1]",
    "mixer_partial0.pipe5.port_a.m_flow",
    "mixer_partial0.pipe5.port_a.p",
    "mixer_partial0.pipe5.port_b.m_flow",
    "mixer_partial0.pipe_out.flowModel.m_flows[1]",
    "mixer_partial0.pipe_out.port_a.m_flow",
    "mixer_partial0.pipe_out.port_a.p",
    "mixer_partial0.pipe_out.port_b.m_flow",
    "mixer_partial0.pipe_out.port_b.p",
    "mixer_partial0.port_in1.m_flow",
    "mixer_partial0.port_in2.m_flow",
    "mixer_partial0.port_in3.m_flow",
    "mixer_partial0.port_out.m_flow",
    "mixer_partial0.pump_P201.N_in_internal",
    "mixer_partial0.pump_P201.port_a.m_flow",
    "mixer_partial0.pump_P201.port_a.p",
    "mixer_partial0.pump_P201.port_b.m_flow",
    "mixer_partial0.pump_P201.port_b.p",
    "mixer_partial0.sink.ports[1].m_flow",
    "mixer_partial0.tank_B201.fluidVolume",
    "mixer_partial0.tank_B201.ports[1].m_flow",
    "mixer_partial0.tank_B201.ports[2].m_flow",
    "mixer_partial0.tank_B202.fluidVolume",
    "mixer_partial0.tank_B202.ports[1].m_flow",
    "mixer_partial0.tank_B202.ports[2].m_flow",
    "mixer_partial0.tank_B203.fluidVolume",
    "mixer_partial0.tank_B203.ports[1].m_flow",
    "mixer_partial0.tank_B203.ports[2].m_flow",
    "mixer_partial0.tank_B204.fluidVolume",
    "mixer_partial0.tank_B204.ports[1].m_flow",
    "mixer_partial0.tank_B204.ports[2].m_flow",
    "mixer_partial0.tank_reservoir.fluidVolume",
    "mixer_partial0.tank_reservoir.ports[1].m_flow",
    "mixer_partial0.tank_reservoir.ports[2].m_flow",
    "mixer_partial0.tank_reservoir.ports[3].m_flow",
    "mixer_partial0.tank_reservoir.ports[4].m_flow",
    "mixer_partial0.valveDiscrete.m_flow",
    "mixer_partial0.valveDiscrete.port_a.m_flow",
    "mixer_partial0.valveDiscrete.port_a.p",
    "mixer_partial0.valveDiscrete.port_b.m_flow",
    "mixer_partial0.valveDiscrete.port_b.p",
    "mixer_partial0.valve_V201.port_a.m_flow",
    "mixer_partial0.valve_V201.port_a.p",
    "mixer_partial0.valve_V201.port_b.m_flow",
    "mixer_partial0.valve_V201.port_b.p",
    "mixer_partial0.valve_V202.port_a.m_flow",
    "mixer_partial0.valve_V202.port_a.p",
    "mixer_partial0.valve_V202.port_b.m_flow",
    "mixer_partial0.valve_V202.port_b.p",
    "mixer_partial0.valve_V203.port_a.m_flow",
    "mixer_partial0.valve_V203.port_a.p",
    "mixer_partial0.valve_V203.port_b.m_flow",
    "mixer_partial0.valve_V203.port_b.p",
    "mixer_partial0.valve_V204.port_a.m_flow",
    "mixer_partial0.valve_V204.port_a.p",
    "mixer_partial0.valve_V204.port_b.m_flow",
    "mixer_partial0.valve_V204.port_b.p",
    "mixer_partial0.valve_clogging.m_flow",
    "mixer_partial0.valve_clogging.opening",
    "mixer_partial0.valve_clogging.port_a.m_flow",
    "mixer_partial0.valve_clogging.port_a.p",
    "mixer_partial0.valve_clogging.port_b.m_flow",
    "mixer_partial0.valve_in1.m_flow",
    "mixer_partial0.valve_in1.port_a.m_flow",
    "mixer_partial0.valve_in1.port_a.p",
    "mixer_partial0.valve_in1.port_b.m_flow",
    "mixer_partial0.valve_in1.port_b.p",
    "mixer_partial0.valve_in2.m_flow",
    "mixer_partial0.valve_in2.port_a.m_flow",
    "mixer_partial0.valve_in2.port_a.p",
    "mixer_partial0.valve_in2.port_b.m_flow",
    "mixer_partial0.valve_in2.port_b.p",
    "mixer_partial0.valve_in3.m_flow",
    "mixer_partial0.valve_in3.port_a.m_flow",
    "mixer_partial0.valve_in3.port_a.p",
    "mixer_partial0.valve_in3.port_b.m_flow",
    "mixer_partial0.valve_in3.port_b.p",
    "mixer_partial0.valve_leaking.opening",
    "mixer_partial0.valve_leaking.port_a.m_flow",
    "mixer_partial0.valve_leaking.port_a.p",
    "mixer_partial0.valve_leaking.port_b.m_flow",
    "mixer_partial0.valve_leaking.port_b.p",
    "sink0.pipe.port_a.m_flow",
    "sink0.pipe.port_a.p",
    "sink0.pipe.port_b.m_flow",
    "sink0.port_in.m_flow",
    "sink0.sink.ports[1].m_flow",
    "sink0.volumeFlowRate.port_a.m_flow",
    "sink0.volumeFlowRate.port_b.m_flow",
    "source0.pipe_out.port_a.m_flow",
    "source0.pipe_out.port_b.m_flow",
    "source0.pipe_out.port_b.p",
    "source0.port_out.m_flow",
    "source0.source.ports[1].m_flow",
    "source0.volumeFlowRate.port_a.m_flow",
    "source0.volumeFlowRate.port_b.m_flow",
    "source1.pipe_out.port_a.m_flow",
    "source1.pipe_out.port_b.m_flow",
    "source1.pipe_out.port_b.p",
    "source1.port_out.m_flow",
    "source1.source.ports[1].m_flow",
    "source1.volumeFlowRate.port_a.m_flow",
    "source1.volumeFlowRate.port_b.m_flow",
    "source2.pipe_out.port_a.m_flow",
    "source2.pipe_out.port_b.m_flow",
    "source2.pipe_out.port_b.p",
    "source2.port_out.m_flow",
    "source2.source.ports[1].m_flow",
    "source2.volumeFlowRate.port_a.m_flow",
    "source2.volumeFlowRate.port_b.m_flow",
]

BERFIPL_RAW_DATA_PATH_NORMAL = "data/raw/data/ds1/ds1n.csv"

